golden_web_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('menu_manager.urls', 'menu_manager'), namespace="menu_manager"))
]

menu_manager/urls.py
from django.urls import path
from menu_manager import views


urlpatterns = [
    path('language/change', views.change_language, name="change_language"),
    path('', views.index, name="index")
]

menu_manager/models/language.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Language(models.Model):

    name = models.CharField(_("Name"), max_length=50)
    code = models.CharField(_("Code"), max_length=5)

    def __str__(self):
        return f'{self.name}({self.code})'

    class Meta:
        verbose_name = _("Language")
        verbose_name_plural = _("Languages")

menu_manager/models/menu_item.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class MenuItem(models.Model):
    '''
        Model present menu item, which can be subitem and has parent item
    '''
    is_root = models.BooleanField(_("Is root element"), default=False)  # If menu item is root component - will render as start point at menu, each such element is different menu
    parent_item = models.ForeignKey(
        "self", verbose_name=_("Parent item"),
        on_delete=models.CASCADE, related_name="child_items",
        null=True, blank=True
    )  # parent item will be rendered as menu and this item as child item
    name = models.CharField(_("Name"), max_length=50)
    link = models.URLField(_("Link"), max_length=200, null=True, blank=True)  # Ignored for items which has childs

    def get_some(self, request):
        return [request.get_full_path()]

    def __str__(self):
        return f'{self.name}//{_("Parent")}: {self.parent_item}'

    class Meta:
        verbose_name = _("Menu item")
        verbose_name_plural = _("Menu items")

menu_manager/models/translation_menu_item.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class TranslationMenuItem(models.Model):
    
    language = models.ForeignKey(
        "menu_manager.Language",
        verbose_name=_("Language"),
        on_delete=models.CASCADE
    )
    menu_item = models.ForeignKey(
        "menu_manager.MenuItem",
        verbose_name=_("Menu item"),
        on_delete=models.CASCADE,
        related_name="translations"
    )
    translated_name = models.CharField(_("Translated name"), max_length=50)

    def __str__(self):
        return f'<Item: {self.menu_item}> Lang: {self.language.name}'

    class Meta:
        verbose_name = _("Menu item translation")
        verbose_name = _("Menu items translation")

menu_manager/views/index.py
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _

from menu_manager import models


def index(request):
    root_menu_items = models.MenuItem.objects.filter(is_root=True).all()
    languages = models.Language.objects.all()
    selected_language = request.session.get('language', 'en-us')
    return render(
        request, 'menu_manager/index.html',
        {
            'menu_list': root_menu_items,
            'languages': languages,
            'selected_language': selected_language
        }
    )

menu_manager/views/languages.py
from django.shortcuts import redirect
from django.http import HttpResponseBadRequest


def change_language(request):
    next_url = request.POST.get('next', '/')
    new_language = request.POST.get('new_language')
    if new_language is None:
        return HttpResponseBadRequest()
    
    request.session['language'] = new_language
    print(request.session)
    return redirect(next_url)

menu_manager/templates/base.html
<!DOCTYPE html>
<html lang="ua">
    <head>
        <title>{% block title %}{% endblock title %}</title>
        <meta charset="utf-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
        {% block head %}{% endblock head %}
        <style>
            .dropdown-menu .dropdown-menu {
                top: auto;
                left: 100%;
                transform: translateY(-2rem);
            }
            .dropdown-item + .dropdown-menu {
                display: none;
            }
            .dropdown-item.submenu::after {
                content: '▸';
                margin-left: 0.5rem;
            }
            .dropdown-item:hover + .dropdown-menu,
            .dropdown-menu:hover {
                display: block;
            }
        </style>
    </head>
    <body>
        {% block content %}{% endblock content %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
        {% block scripts %}{% endblock scripts %}
    </body>
</html>

menu_manager/templates/menu_manager/index.html
{% extends 'base.html' %}
{% block content %}
    {% load translate_menu_item %}
    {% load i18n %}
    <div class="d-flex justify-content-between">
        {% for item in menu_list %}
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="item_{{item.id}}" data-bs-toggle="dropdown" aria-expanded="false">
                    {% translate_menu_item item.id "name" %}
                </button>
                <div class="dropdown-menu" aria-labelledby="item_{{item.id}}">
                    {% for child_item in item.child_items.all %}
                        {% include 'menu_manager/menu_item.html' with item=child_item %}
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
        <a href="{% url 'admin:index' %}" class="btn btn-primary">Administration</a>
        <form action="{% url 'menu_manager:change_language' %}" method="post">
            {% csrf_token %}
            <input hidden value="{{request.get_full_path}}" name="next"/>
            <select class="form-select" name="new_language">
                {% for language in languages %}
                    <option
                        value="{{language.code}}"
                        {% if language.code == selected_language %} selected {% endif %}
                    >
                        {{language.name}}
                    </option>
                {% endfor %}
            </select>
            <input type="submit" value="Change language">
        </form>
    </div>
{% endblock content %}
{% block scripts %}
<script>
    $(document).ready(() => {
        $('.tree-toggle').click(function () {
            $(this).parent().children('ul.tree').toggle(200);
        });
    });
</script>
{% endblock scripts %}

menu_manager/templates/menu_manager/menu_item.html
{% load translate_menu_item %}

{% if item.child_items.all %}
    <a href="#" class="dropdown-item submenu" role="menu" type="button" id="item_{{item.id}}" data-bs-toggle="dropdown" aria-expanded="false">
        {% translate_menu_item item.id "name" %}
    </a>
    <div class="dropdown-menu" aria-labelledby="item_{{item.id}}">
        {% for child_item in item.child_items.all %}
            {% include 'menu_manager/menu_item.html' with item=child_item %}
        {% endfor %}
    </div>
{% else %}
    <a class="dropdown-item" type="button" id="item_{{item.id}}" href="{{item.link}}">
        {% translate_menu_item item.id "name" %}
    </a>
{% endif %}